spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.properties.hibernate.dialect=${DATABASE_DIALECT}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret = afdc5c0e1f3862c3e38d537348ea20dfe97edc37c40f653af9a47a0ae3325c6e
jwt.expiration = 172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.com.example.urlshortener=DEBUG

frontend.url = http://localhost:5173